//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaGestionCEM.Negocio.ws_estado_alumnos {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://WebService/", ConfigurationName="ws_estado_alumnos.WebServiceCEM")]
    public interface WebServiceCEM {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://WebService/WebServiceCEM/obtenerEstadoAlumnosRequest", ReplyAction="http://WebService/WebServiceCEM/obtenerEstadoAlumnosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SistemaGestionCEM.Negocio.ws_estado_alumnos.obtenerEstadoAlumnosResponse obtenerEstadoAlumnos(SistemaGestionCEM.Negocio.ws_estado_alumnos.obtenerEstadoAlumnosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebService/WebServiceCEM/obtenerEstadoAlumnosRequest", ReplyAction="http://WebService/WebServiceCEM/obtenerEstadoAlumnosResponse")]
        System.Threading.Tasks.Task<SistemaGestionCEM.Negocio.ws_estado_alumnos.obtenerEstadoAlumnosResponse> obtenerEstadoAlumnosAsync(SistemaGestionCEM.Negocio.ws_estado_alumnos.obtenerEstadoAlumnosRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://WebService/")]
    public partial class alumno : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codigoAlumnoField;
        
        private string nombreAlumnoField;
        
        private string apellidoAlumnoField;
        
        private string estadoAlumnoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int codigoAlumno {
            get {
                return this.codigoAlumnoField;
            }
            set {
                this.codigoAlumnoField = value;
                this.RaisePropertyChanged("codigoAlumno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombreAlumno {
            get {
                return this.nombreAlumnoField;
            }
            set {
                this.nombreAlumnoField = value;
                this.RaisePropertyChanged("nombreAlumno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string apellidoAlumno {
            get {
                return this.apellidoAlumnoField;
            }
            set {
                this.apellidoAlumnoField = value;
                this.RaisePropertyChanged("apellidoAlumno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string estadoAlumno {
            get {
                return this.estadoAlumnoField;
            }
            set {
                this.estadoAlumnoField = value;
                this.RaisePropertyChanged("estadoAlumno");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerEstadoAlumnos", WrapperNamespace="http://WebService/", IsWrapped=true)]
    public partial class obtenerEstadoAlumnosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebService/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombreAlumno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebService/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string apellidoAlumno;
        
        public obtenerEstadoAlumnosRequest() {
        }
        
        public obtenerEstadoAlumnosRequest(string nombreAlumno, string apellidoAlumno) {
            this.nombreAlumno = nombreAlumno;
            this.apellidoAlumno = apellidoAlumno;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerEstadoAlumnosResponse", WrapperNamespace="http://WebService/", IsWrapped=true)]
    public partial class obtenerEstadoAlumnosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebService/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SistemaGestionCEM.Negocio.ws_estado_alumnos.alumno @return;
        
        public obtenerEstadoAlumnosResponse() {
        }
        
        public obtenerEstadoAlumnosResponse(SistemaGestionCEM.Negocio.ws_estado_alumnos.alumno @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceCEMChannel : SistemaGestionCEM.Negocio.ws_estado_alumnos.WebServiceCEM, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceCEMClient : System.ServiceModel.ClientBase<SistemaGestionCEM.Negocio.ws_estado_alumnos.WebServiceCEM>, SistemaGestionCEM.Negocio.ws_estado_alumnos.WebServiceCEM {
        
        public WebServiceCEMClient() {
        }
        
        public WebServiceCEMClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceCEMClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceCEMClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceCEMClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SistemaGestionCEM.Negocio.ws_estado_alumnos.obtenerEstadoAlumnosResponse SistemaGestionCEM.Negocio.ws_estado_alumnos.WebServiceCEM.obtenerEstadoAlumnos(SistemaGestionCEM.Negocio.ws_estado_alumnos.obtenerEstadoAlumnosRequest request) {
            return base.Channel.obtenerEstadoAlumnos(request);
        }
        
        public SistemaGestionCEM.Negocio.ws_estado_alumnos.alumno obtenerEstadoAlumnos(string nombreAlumno, string apellidoAlumno) {
            SistemaGestionCEM.Negocio.ws_estado_alumnos.obtenerEstadoAlumnosRequest inValue = new SistemaGestionCEM.Negocio.ws_estado_alumnos.obtenerEstadoAlumnosRequest();
            inValue.nombreAlumno = nombreAlumno;
            inValue.apellidoAlumno = apellidoAlumno;
            SistemaGestionCEM.Negocio.ws_estado_alumnos.obtenerEstadoAlumnosResponse retVal = ((SistemaGestionCEM.Negocio.ws_estado_alumnos.WebServiceCEM)(this)).obtenerEstadoAlumnos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SistemaGestionCEM.Negocio.ws_estado_alumnos.obtenerEstadoAlumnosResponse> SistemaGestionCEM.Negocio.ws_estado_alumnos.WebServiceCEM.obtenerEstadoAlumnosAsync(SistemaGestionCEM.Negocio.ws_estado_alumnos.obtenerEstadoAlumnosRequest request) {
            return base.Channel.obtenerEstadoAlumnosAsync(request);
        }
        
        public System.Threading.Tasks.Task<SistemaGestionCEM.Negocio.ws_estado_alumnos.obtenerEstadoAlumnosResponse> obtenerEstadoAlumnosAsync(string nombreAlumno, string apellidoAlumno) {
            SistemaGestionCEM.Negocio.ws_estado_alumnos.obtenerEstadoAlumnosRequest inValue = new SistemaGestionCEM.Negocio.ws_estado_alumnos.obtenerEstadoAlumnosRequest();
            inValue.nombreAlumno = nombreAlumno;
            inValue.apellidoAlumno = apellidoAlumno;
            return ((SistemaGestionCEM.Negocio.ws_estado_alumnos.WebServiceCEM)(this)).obtenerEstadoAlumnosAsync(inValue);
        }
    }
}
