//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaGestionCEM.Datos
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class ALUMNO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ALUMNO()
        {
            this.DETALLE_ALUMNO = new HashSet<DETALLE_ALUMNO>();
            this.POSTULACION_ALUMNO = new HashSet<POSTULACION_ALUMNO>();
        }
    
        public decimal COD_ALUMNO { get; set; }

        [DataType(DataType.Date)]
        [Required(ErrorMessage ="La fecha de nacimiento es obligatoria", AllowEmptyStrings = false)]
        [DisplayName("Fecha de Nacimiento")]
        public System.DateTime FECHA_NACIMIENTO { get; set; }

        public decimal FK_COD_PERSONA { get; set; }

        [Required]
        public virtual PERSONA PERSONA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_ALUMNO> DETALLE_ALUMNO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POSTULACION_ALUMNO> POSTULACION_ALUMNO { get; set; }
    }
}
