//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaGestionCEM.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANTECEDENTES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ANTECEDENTES()
        {
            this.FAMILIA_ANFITRIONA = new HashSet<FAMILIA_ANFITRIONA>();
        }
    
        public decimal COD_ANTECEDENTES { get; set; }
        public string FOTO1 { get; set; }
        public string FOTO2 { get; set; }
        public string FOTO3 { get; set; }
        public string CERT_RESIDENCIA { get; set; }
        public string CERT_ANTECEDENTES { get; set; }
        public string CERT_LABORAL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FAMILIA_ANFITRIONA> FAMILIA_ANFITRIONA { get; set; }
    }
}
