//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaGestionCEM.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CENTRO_ESTUDIO_LOCAL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CENTRO_ESTUDIO_LOCAL()
        {
            this.ENCARGADO_CEL = new HashSet<ENCARGADO_CEL>();
            this.POSTULACION_PROGRAMA = new HashSet<POSTULACION_PROGRAMA>();
        }
    
        public decimal COD_CEL { get; set; }
        public string NOMBRE_CENTRO { get; set; }
        public string NOM_DIRECTOR { get; set; }
        public string AREA_ESPECIALIZACION { get; set; }
        public string DIRECCION { get; set; }
        public string CORREO { get; set; }
        public decimal TELEFONO { get; set; }
        public string DESCRIPCION { get; set; }
        public decimal FK_COD_CIUDAD { get; set; }
    
        public virtual CIUDAD CIUDAD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ENCARGADO_CEL> ENCARGADO_CEL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POSTULACION_PROGRAMA> POSTULACION_PROGRAMA { get; set; }
    }
}
