//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaGestionCEM.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_NOTAS
    {
        public decimal COD_NOTAS { get; set; }
        public Nullable<decimal> NOTA1 { get; set; }
        public Nullable<decimal> NOTA2 { get; set; }
        public Nullable<decimal> NOTA3 { get; set; }
        public Nullable<decimal> NOTA4 { get; set; }
        public Nullable<decimal> PROMEDIO { get; set; }
        public decimal FK_COD_DETALUMNO { get; set; }
    
        public virtual DETALLE_ALUMNO DETALLE_ALUMNO { get; set; }
    }
}
