//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaGestionCEM.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_ALUMNO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DETALLE_ALUMNO()
        {
            this.DETALLE_NOTAS = new HashSet<DETALLE_NOTAS>();
        }
    
        public decimal COD_DETALUMNO { get; set; }
        public string ESTADO_ALUMNO { get; set; }
        public decimal FK_COD_ALUMNO { get; set; }
        public decimal FK_COD_PROGRAMA { get; set; }
    
        public virtual ALUMNO ALUMNO { get; set; }
        public virtual PROGRAMA_ESTUDIO PROGRAMA_ESTUDIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_NOTAS> DETALLE_NOTAS { get; set; }
    }
}
