//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaGestionCEM.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENCARGADO_CEM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ENCARGADO_CEM()
        {
            this.POSTULACION_PROGRAMA = new HashSet<POSTULACION_PROGRAMA>();
            this.PROGRAMA_ESTUDIO = new HashSet<PROGRAMA_ESTUDIO>();
            this.POSTULACION_ALUMNO = new HashSet<POSTULACION_ALUMNO>();
        }
    
        public decimal COD_ENCARGADOCEM { get; set; }
        public decimal FK_COD_PERSONA { get; set; }
    
        public virtual PERSONA PERSONA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POSTULACION_PROGRAMA> POSTULACION_PROGRAMA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROGRAMA_ESTUDIO> PROGRAMA_ESTUDIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POSTULACION_ALUMNO> POSTULACION_ALUMNO { get; set; }
    }
}
