//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaGestionCEM.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENCARGADO_CEL
    {
        public decimal COD_ENCARGADOCEL { get; set; }
        public decimal FK_COD_PERSONA { get; set; }
        public decimal FK_COD_CEL { get; set; }
    
        public virtual CENTRO_ESTUDIO_LOCAL CENTRO_ESTUDIO_LOCAL { get; set; }
        public virtual PERSONA PERSONA { get; set; }
    }
}
