//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaGestionCEM.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAMILIA_ANFITRIONA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FAMILIA_ANFITRIONA()
        {
            this.POSTULACION_ALUMNO = new HashSet<POSTULACION_ALUMNO>();
        }
    
        public decimal COD_FAMILIA { get; set; }
        public decimal NUM_INTEGRANTES { get; set; }
        public decimal NUM_HABITACIONES { get; set; }
        public decimal NUM_BANOS { get; set; }
        public string TIPO_VIVIENDA { get; set; }
        public string ESTACIONAMIENTO { get; set; }
        public string MASCOTA_DESCRIPCION { get; set; }
        public decimal ANIO_INSCRIPCION { get; set; }
        public decimal FK_COD_PERSONA { get; set; }
        public decimal FK_COD_ANTECEDENTES { get; set; }
    
        public virtual ANTECEDENTES ANTECEDENTES { get; set; }
        public virtual PERSONA PERSONA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POSTULACION_ALUMNO> POSTULACION_ALUMNO { get; set; }
    }
}
