//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaGestionCEM.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PERSONA()
        {
            this.ALUMNO = new HashSet<ALUMNO>();
            this.ENCARGADO_CEL = new HashSet<ENCARGADO_CEL>();
            this.ENCARGADO_CEM = new HashSet<ENCARGADO_CEM>();
            this.FAMILIA_ANFITRIONA = new HashSet<FAMILIA_ANFITRIONA>();
        }
    
        public decimal COD_PERSONA { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDO { get; set; }
        public string CORREO { get; set; }
        public decimal TELEFONO { get; set; }
        public string NACIONALIDAD { get; set; }
        public decimal FK_COD_CIUDAD { get; set; }
        public decimal FK_COD_GENERO { get; set; }
        public decimal FK_COD_USUARIO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ALUMNO> ALUMNO { get; set; }
        public virtual CIUDAD CIUDAD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ENCARGADO_CEL> ENCARGADO_CEL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ENCARGADO_CEM> ENCARGADO_CEM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FAMILIA_ANFITRIONA> FAMILIA_ANFITRIONA { get; set; }
        public virtual GENERO GENERO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
