//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaGestionCEM.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class POSTULACION_PROGRAMA
    {
        public decimal COD_POSTULACIONPROGRAMA { get; set; }
        public System.DateTime FECHA { get; set; }
        public decimal FK_COD_CEL { get; set; }
        public decimal FK_COD_PROGRAMA { get; set; }
        public decimal FK_COD_ESTADO { get; set; }
        public decimal FK_COD_ENCARGADOCEM { get; set; }
    
        public virtual CENTRO_ESTUDIO_LOCAL CENTRO_ESTUDIO_LOCAL { get; set; }
        public virtual ENCARGADO_CEM ENCARGADO_CEM { get; set; }
        public virtual ESTADO_POSTULACION ESTADO_POSTULACION { get; set; }
        public virtual PROGRAMA_ESTUDIO PROGRAMA_ESTUDIO { get; set; }
    }
}
