//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaGestionCEM.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROGRAMA_ESTUDIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROGRAMA_ESTUDIO()
        {
            this.DETALLE_ALUMNO = new HashSet<DETALLE_ALUMNO>();
            this.POSTULACION_ALUMNO = new HashSet<POSTULACION_ALUMNO>();
            this.POSTULACION_PROGRAMA = new HashSet<POSTULACION_PROGRAMA>();
        }
    
        public decimal COD_PROGRAMA { get; set; }
        public string NOMBRE_PROGRAMA { get; set; }
        public string DESCRIPCION { get; set; }
        public System.DateTime FECHA_LIMITE_POSTULACION { get; set; }
        public string AREA_CONOCIMIENTO { get; set; }
        public string DURACION { get; set; }
        public decimal NUM_MAX_ALUMNO { get; set; }
        public decimal NUM_MIN_ALUMNO { get; set; }
        public decimal FK_COD_TIPOPROGRAMA { get; set; }
        public decimal FK_COD_ENCARGADOCEM { get; set; }
        public decimal FK_COD_PAIS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_ALUMNO> DETALLE_ALUMNO { get; set; }
        public virtual ENCARGADO_CEM ENCARGADO_CEM { get; set; }
        public virtual PAIS PAIS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POSTULACION_ALUMNO> POSTULACION_ALUMNO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POSTULACION_PROGRAMA> POSTULACION_PROGRAMA { get; set; }
        public virtual TIPO_PROGRAMA TIPO_PROGRAMA { get; set; }
    }
}
