//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaGestionCEM.Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ALUMNO> ALUMNO { get; set; }
        public virtual DbSet<ANTECEDENTES> ANTECEDENTES { get; set; }
        public virtual DbSet<CENTRO_ESTUDIO_LOCAL> CENTRO_ESTUDIO_LOCAL { get; set; }
        public virtual DbSet<CIUDAD> CIUDAD { get; set; }
        public virtual DbSet<DETALLE_ALUMNO> DETALLE_ALUMNO { get; set; }
        public virtual DbSet<DETALLE_NOTAS> DETALLE_NOTAS { get; set; }
        public virtual DbSet<ENCARGADO_CEL> ENCARGADO_CEL { get; set; }
        public virtual DbSet<ENCARGADO_CEM> ENCARGADO_CEM { get; set; }
        public virtual DbSet<ESTADO_POSTULACION> ESTADO_POSTULACION { get; set; }
        public virtual DbSet<FAMILIA_ANFITRIONA> FAMILIA_ANFITRIONA { get; set; }
        public virtual DbSet<GENERO> GENERO { get; set; }
        public virtual DbSet<PAIS> PAIS { get; set; }
        public virtual DbSet<PERSONA> PERSONA { get; set; }
        public virtual DbSet<POSTULACION_ALUMNO> POSTULACION_ALUMNO { get; set; }
        public virtual DbSet<POSTULACION_PROGRAMA> POSTULACION_PROGRAMA { get; set; }
        public virtual DbSet<PROGRAMA_ESTUDIO> PROGRAMA_ESTUDIO { get; set; }
        public virtual DbSet<TIPO_PROGRAMA> TIPO_PROGRAMA { get; set; }
        public virtual DbSet<TIPO_USUARIO> TIPO_USUARIO { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }

        public int GetNextSequenceValuePostulacionAlumno()
        {
            var rawQuery = Database.SqlQuery<int>("SELECT SEQ_POSALUMNO.NEXTVAL FROM dual");
            var task = rawQuery.SingleAsync();
            int nextVal = task.Result;

            return nextVal;
        }
    }
}
