//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaGestionCEM.Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ALUMNO> ALUMNO { get; set; }
        public virtual DbSet<ANTECEDENTES> ANTECEDENTES { get; set; }
        public virtual DbSet<CENTRO_ESTUDIO_LOCAL> CENTRO_ESTUDIO_LOCAL { get; set; }
        public virtual DbSet<CIUDAD> CIUDAD { get; set; }
        public virtual DbSet<DETALLE_ALUMNO> DETALLE_ALUMNO { get; set; }
        public virtual DbSet<DETALLE_NOTAS> DETALLE_NOTAS { get; set; }
        public virtual DbSet<ENCARGADO_CEL> ENCARGADO_CEL { get; set; }
        public virtual DbSet<ENCARGADO_CEM> ENCARGADO_CEM { get; set; }
        public virtual DbSet<ESTADO_POSTULACION> ESTADO_POSTULACION { get; set; }
        public virtual DbSet<FAMILIA_ANFITRIONA> FAMILIA_ANFITRIONA { get; set; }
        public virtual DbSet<GENERO> GENERO { get; set; }
        public virtual DbSet<PAIS> PAIS { get; set; }
        public virtual DbSet<PERSONA> PERSONA { get; set; }
        public virtual DbSet<POSTULACION_ALUMNO> POSTULACION_ALUMNO { get; set; }
        public virtual DbSet<POSTULACION_PROGRAMA> POSTULACION_PROGRAMA { get; set; }
        public virtual DbSet<PROGRAMA_ESTUDIO> PROGRAMA_ESTUDIO { get; set; }
        public virtual DbSet<TIPO_PROGRAMA> TIPO_PROGRAMA { get; set; }
        public virtual DbSet<TIPO_USUARIO> TIPO_USUARIO { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
    
        public virtual int CrearUsuario(string p_CONTRASENNA, Nullable<decimal> p_COD_USUARIO, string p_NOMBRE_USUARIO, Nullable<decimal> p_FK_COD_TIPO)
        {
            var p_CONTRASENNAParameter = p_CONTRASENNA != null ?
                new ObjectParameter("P_CONTRASENNA", p_CONTRASENNA) :
                new ObjectParameter("P_CONTRASENNA", typeof(string));
    
            var p_COD_USUARIOParameter = p_COD_USUARIO.HasValue ?
                new ObjectParameter("P_COD_USUARIO", p_COD_USUARIO) :
                new ObjectParameter("P_COD_USUARIO", typeof(decimal));
    
            var p_NOMBRE_USUARIOParameter = p_NOMBRE_USUARIO != null ?
                new ObjectParameter("P_NOMBRE_USUARIO", p_NOMBRE_USUARIO) :
                new ObjectParameter("P_NOMBRE_USUARIO", typeof(string));
    
            var p_FK_COD_TIPOParameter = p_FK_COD_TIPO.HasValue ?
                new ObjectParameter("P_FK_COD_TIPO", p_FK_COD_TIPO) :
                new ObjectParameter("P_FK_COD_TIPO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CrearUsuario", p_CONTRASENNAParameter, p_COD_USUARIOParameter, p_NOMBRE_USUARIOParameter, p_FK_COD_TIPOParameter);
        }
    
        public virtual int ActualizarUsuario(string p_CONTRASENNA, Nullable<decimal> p_COD_USUARIO, string p_NOMBRE_USUARIO, Nullable<decimal> p_FK_COD_TIPO)
        {
            var p_CONTRASENNAParameter = p_CONTRASENNA != null ?
                new ObjectParameter("P_CONTRASENNA", p_CONTRASENNA) :
                new ObjectParameter("P_CONTRASENNA", typeof(string));
    
            var p_COD_USUARIOParameter = p_COD_USUARIO.HasValue ?
                new ObjectParameter("P_COD_USUARIO", p_COD_USUARIO) :
                new ObjectParameter("P_COD_USUARIO", typeof(decimal));
    
            var p_NOMBRE_USUARIOParameter = p_NOMBRE_USUARIO != null ?
                new ObjectParameter("P_NOMBRE_USUARIO", p_NOMBRE_USUARIO) :
                new ObjectParameter("P_NOMBRE_USUARIO", typeof(string));
    
            var p_FK_COD_TIPOParameter = p_FK_COD_TIPO.HasValue ?
                new ObjectParameter("P_FK_COD_TIPO", p_FK_COD_TIPO) :
                new ObjectParameter("P_FK_COD_TIPO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ActualizarUsuario", p_CONTRASENNAParameter, p_COD_USUARIOParameter, p_NOMBRE_USUARIOParameter, p_FK_COD_TIPOParameter);
        }
    
        public virtual int EliminarUsuario(Nullable<decimal> p_COD_USUARIO)
        {
            var p_COD_USUARIOParameter = p_COD_USUARIO.HasValue ?
                new ObjectParameter("P_COD_USUARIO", p_COD_USUARIO) :
                new ObjectParameter("P_COD_USUARIO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EliminarUsuario", p_COD_USUARIOParameter);
        }
    
        public virtual int CrearAlumno(Nullable<decimal> p_COD_ALUMNO, Nullable<decimal> p_FK_COD_PERSONA, Nullable<System.DateTime> p_FECHA_NACIMIENTO)
        {
            var p_COD_ALUMNOParameter = p_COD_ALUMNO.HasValue ?
                new ObjectParameter("P_COD_ALUMNO", p_COD_ALUMNO) :
                new ObjectParameter("P_COD_ALUMNO", typeof(decimal));
    
            var p_FK_COD_PERSONAParameter = p_FK_COD_PERSONA.HasValue ?
                new ObjectParameter("P_FK_COD_PERSONA", p_FK_COD_PERSONA) :
                new ObjectParameter("P_FK_COD_PERSONA", typeof(decimal));
    
            var p_FECHA_NACIMIENTOParameter = p_FECHA_NACIMIENTO.HasValue ?
                new ObjectParameter("P_FECHA_NACIMIENTO", p_FECHA_NACIMIENTO) :
                new ObjectParameter("P_FECHA_NACIMIENTO", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CrearAlumno", p_COD_ALUMNOParameter, p_FK_COD_PERSONAParameter, p_FECHA_NACIMIENTOParameter);
        }
    
        public virtual int ActualizarAlumno(Nullable<decimal> p_COD_ALUMNO, Nullable<decimal> p_FK_COD_PERSONA, Nullable<System.DateTime> p_FECHA_NACIMIENTO)
        {
            var p_COD_ALUMNOParameter = p_COD_ALUMNO.HasValue ?
                new ObjectParameter("P_COD_ALUMNO", p_COD_ALUMNO) :
                new ObjectParameter("P_COD_ALUMNO", typeof(decimal));
    
            var p_FK_COD_PERSONAParameter = p_FK_COD_PERSONA.HasValue ?
                new ObjectParameter("P_FK_COD_PERSONA", p_FK_COD_PERSONA) :
                new ObjectParameter("P_FK_COD_PERSONA", typeof(decimal));
    
            var p_FECHA_NACIMIENTOParameter = p_FECHA_NACIMIENTO.HasValue ?
                new ObjectParameter("P_FECHA_NACIMIENTO", p_FECHA_NACIMIENTO) :
                new ObjectParameter("P_FECHA_NACIMIENTO", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ActualizarAlumno", p_COD_ALUMNOParameter, p_FK_COD_PERSONAParameter, p_FECHA_NACIMIENTOParameter);
        }
    
        public virtual int EliminarAlumno(Nullable<decimal> p_COD_ALUMNO)
        {
            var p_COD_ALUMNOParameter = p_COD_ALUMNO.HasValue ?
                new ObjectParameter("P_COD_ALUMNO", p_COD_ALUMNO) :
                new ObjectParameter("P_COD_ALUMNO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EliminarAlumno", p_COD_ALUMNOParameter);
        }
    
        public virtual int CrearPersona(string p_APELLIDO, string p_CORREO, Nullable<decimal> p_COD_PERSONA, Nullable<decimal> p_TELEFONO, Nullable<decimal> p_FK_COD_USUARIO, string p_NACIONALIDAD, Nullable<decimal> p_FK_COD_CIUDAD, string p_NOMBRE, Nullable<decimal> p_FK_COD_GENERO)
        {
            var p_APELLIDOParameter = p_APELLIDO != null ?
                new ObjectParameter("P_APELLIDO", p_APELLIDO) :
                new ObjectParameter("P_APELLIDO", typeof(string));
    
            var p_CORREOParameter = p_CORREO != null ?
                new ObjectParameter("P_CORREO", p_CORREO) :
                new ObjectParameter("P_CORREO", typeof(string));
    
            var p_COD_PERSONAParameter = p_COD_PERSONA.HasValue ?
                new ObjectParameter("P_COD_PERSONA", p_COD_PERSONA) :
                new ObjectParameter("P_COD_PERSONA", typeof(decimal));
    
            var p_TELEFONOParameter = p_TELEFONO.HasValue ?
                new ObjectParameter("P_TELEFONO", p_TELEFONO) :
                new ObjectParameter("P_TELEFONO", typeof(decimal));
    
            var p_FK_COD_USUARIOParameter = p_FK_COD_USUARIO.HasValue ?
                new ObjectParameter("P_FK_COD_USUARIO", p_FK_COD_USUARIO) :
                new ObjectParameter("P_FK_COD_USUARIO", typeof(decimal));
    
            var p_NACIONALIDADParameter = p_NACIONALIDAD != null ?
                new ObjectParameter("P_NACIONALIDAD", p_NACIONALIDAD) :
                new ObjectParameter("P_NACIONALIDAD", typeof(string));
    
            var p_FK_COD_CIUDADParameter = p_FK_COD_CIUDAD.HasValue ?
                new ObjectParameter("P_FK_COD_CIUDAD", p_FK_COD_CIUDAD) :
                new ObjectParameter("P_FK_COD_CIUDAD", typeof(decimal));
    
            var p_NOMBREParameter = p_NOMBRE != null ?
                new ObjectParameter("P_NOMBRE", p_NOMBRE) :
                new ObjectParameter("P_NOMBRE", typeof(string));
    
            var p_FK_COD_GENEROParameter = p_FK_COD_GENERO.HasValue ?
                new ObjectParameter("P_FK_COD_GENERO", p_FK_COD_GENERO) :
                new ObjectParameter("P_FK_COD_GENERO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CrearPersona", p_APELLIDOParameter, p_CORREOParameter, p_COD_PERSONAParameter, p_TELEFONOParameter, p_FK_COD_USUARIOParameter, p_NACIONALIDADParameter, p_FK_COD_CIUDADParameter, p_NOMBREParameter, p_FK_COD_GENEROParameter);
        }
    
        public virtual int ActualizarPersona(string p_APELLIDO, string p_CORREO, Nullable<decimal> p_COD_PERSONA, Nullable<decimal> p_TELEFONO, Nullable<decimal> p_FK_COD_USUARIO, string p_NACIONALIDAD, Nullable<decimal> p_FK_COD_CIUDAD, string p_NOMBRE, Nullable<decimal> p_FK_COD_GENERO)
        {
            var p_APELLIDOParameter = p_APELLIDO != null ?
                new ObjectParameter("P_APELLIDO", p_APELLIDO) :
                new ObjectParameter("P_APELLIDO", typeof(string));
    
            var p_CORREOParameter = p_CORREO != null ?
                new ObjectParameter("P_CORREO", p_CORREO) :
                new ObjectParameter("P_CORREO", typeof(string));
    
            var p_COD_PERSONAParameter = p_COD_PERSONA.HasValue ?
                new ObjectParameter("P_COD_PERSONA", p_COD_PERSONA) :
                new ObjectParameter("P_COD_PERSONA", typeof(decimal));
    
            var p_TELEFONOParameter = p_TELEFONO.HasValue ?
                new ObjectParameter("P_TELEFONO", p_TELEFONO) :
                new ObjectParameter("P_TELEFONO", typeof(decimal));
    
            var p_FK_COD_USUARIOParameter = p_FK_COD_USUARIO.HasValue ?
                new ObjectParameter("P_FK_COD_USUARIO", p_FK_COD_USUARIO) :
                new ObjectParameter("P_FK_COD_USUARIO", typeof(decimal));
    
            var p_NACIONALIDADParameter = p_NACIONALIDAD != null ?
                new ObjectParameter("P_NACIONALIDAD", p_NACIONALIDAD) :
                new ObjectParameter("P_NACIONALIDAD", typeof(string));
    
            var p_FK_COD_CIUDADParameter = p_FK_COD_CIUDAD.HasValue ?
                new ObjectParameter("P_FK_COD_CIUDAD", p_FK_COD_CIUDAD) :
                new ObjectParameter("P_FK_COD_CIUDAD", typeof(decimal));
    
            var p_NOMBREParameter = p_NOMBRE != null ?
                new ObjectParameter("P_NOMBRE", p_NOMBRE) :
                new ObjectParameter("P_NOMBRE", typeof(string));
    
            var p_FK_COD_GENEROParameter = p_FK_COD_GENERO.HasValue ?
                new ObjectParameter("P_FK_COD_GENERO", p_FK_COD_GENERO) :
                new ObjectParameter("P_FK_COD_GENERO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ActualizarPersona", p_APELLIDOParameter, p_CORREOParameter, p_COD_PERSONAParameter, p_TELEFONOParameter, p_FK_COD_USUARIOParameter, p_NACIONALIDADParameter, p_FK_COD_CIUDADParameter, p_NOMBREParameter, p_FK_COD_GENEROParameter);
        }
    
        public virtual int EliminarPersona(Nullable<decimal> p_COD_PERSONA)
        {
            var p_COD_PERSONAParameter = p_COD_PERSONA.HasValue ?
                new ObjectParameter("P_COD_PERSONA", p_COD_PERSONA) :
                new ObjectParameter("P_COD_PERSONA", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EliminarPersona", p_COD_PERSONAParameter);
        }
    
        public virtual int CrearFamilia(Nullable<decimal> p_NUM_BANOS, Nullable<decimal> p_FK_COD_ANTECEDENTES, Nullable<decimal> p_COD_FAMILIA, Nullable<decimal> p_ANIO_INSCRIPCION, Nullable<decimal> p_NUM_HABITACIONES, string p_TIPO_VIVIENDA, Nullable<decimal> p_NUM_INTEGRANTES, Nullable<decimal> p_FK_COD_PERSONA, string p_ESTACIONAMIENTO, string p_MASCOTA_DESCRIPCION)
        {
            var p_NUM_BANOSParameter = p_NUM_BANOS.HasValue ?
                new ObjectParameter("P_NUM_BANOS", p_NUM_BANOS) :
                new ObjectParameter("P_NUM_BANOS", typeof(decimal));
    
            var p_FK_COD_ANTECEDENTESParameter = p_FK_COD_ANTECEDENTES.HasValue ?
                new ObjectParameter("P_FK_COD_ANTECEDENTES", p_FK_COD_ANTECEDENTES) :
                new ObjectParameter("P_FK_COD_ANTECEDENTES", typeof(decimal));
    
            var p_COD_FAMILIAParameter = p_COD_FAMILIA.HasValue ?
                new ObjectParameter("P_COD_FAMILIA", p_COD_FAMILIA) :
                new ObjectParameter("P_COD_FAMILIA", typeof(decimal));
    
            var p_ANIO_INSCRIPCIONParameter = p_ANIO_INSCRIPCION.HasValue ?
                new ObjectParameter("P_ANIO_INSCRIPCION", p_ANIO_INSCRIPCION) :
                new ObjectParameter("P_ANIO_INSCRIPCION", typeof(decimal));
    
            var p_NUM_HABITACIONESParameter = p_NUM_HABITACIONES.HasValue ?
                new ObjectParameter("P_NUM_HABITACIONES", p_NUM_HABITACIONES) :
                new ObjectParameter("P_NUM_HABITACIONES", typeof(decimal));
    
            var p_TIPO_VIVIENDAParameter = p_TIPO_VIVIENDA != null ?
                new ObjectParameter("P_TIPO_VIVIENDA", p_TIPO_VIVIENDA) :
                new ObjectParameter("P_TIPO_VIVIENDA", typeof(string));
    
            var p_NUM_INTEGRANTESParameter = p_NUM_INTEGRANTES.HasValue ?
                new ObjectParameter("P_NUM_INTEGRANTES", p_NUM_INTEGRANTES) :
                new ObjectParameter("P_NUM_INTEGRANTES", typeof(decimal));
    
            var p_FK_COD_PERSONAParameter = p_FK_COD_PERSONA.HasValue ?
                new ObjectParameter("P_FK_COD_PERSONA", p_FK_COD_PERSONA) :
                new ObjectParameter("P_FK_COD_PERSONA", typeof(decimal));
    
            var p_ESTACIONAMIENTOParameter = p_ESTACIONAMIENTO != null ?
                new ObjectParameter("P_ESTACIONAMIENTO", p_ESTACIONAMIENTO) :
                new ObjectParameter("P_ESTACIONAMIENTO", typeof(string));
    
            var p_MASCOTA_DESCRIPCIONParameter = p_MASCOTA_DESCRIPCION != null ?
                new ObjectParameter("P_MASCOTA_DESCRIPCION", p_MASCOTA_DESCRIPCION) :
                new ObjectParameter("P_MASCOTA_DESCRIPCION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CrearFamilia", p_NUM_BANOSParameter, p_FK_COD_ANTECEDENTESParameter, p_COD_FAMILIAParameter, p_ANIO_INSCRIPCIONParameter, p_NUM_HABITACIONESParameter, p_TIPO_VIVIENDAParameter, p_NUM_INTEGRANTESParameter, p_FK_COD_PERSONAParameter, p_ESTACIONAMIENTOParameter, p_MASCOTA_DESCRIPCIONParameter);
        }
    
        public virtual int ActualizarFamilia(Nullable<decimal> p_NUM_BANOS, Nullable<decimal> p_FK_COD_ANTECEDENTES, Nullable<decimal> p_COD_FAMILIA, Nullable<decimal> p_ANIO_INSCRIPCION, Nullable<decimal> p_NUM_HABITACIONES, string p_TIPO_VIVIENDA, Nullable<decimal> p_NUM_INTEGRANTES, Nullable<decimal> p_FK_COD_PERSONA, string p_ESTACIONAMIENTO, string p_MASCOTA_DESCRIPCION)
        {
            var p_NUM_BANOSParameter = p_NUM_BANOS.HasValue ?
                new ObjectParameter("P_NUM_BANOS", p_NUM_BANOS) :
                new ObjectParameter("P_NUM_BANOS", typeof(decimal));
    
            var p_FK_COD_ANTECEDENTESParameter = p_FK_COD_ANTECEDENTES.HasValue ?
                new ObjectParameter("P_FK_COD_ANTECEDENTES", p_FK_COD_ANTECEDENTES) :
                new ObjectParameter("P_FK_COD_ANTECEDENTES", typeof(decimal));
    
            var p_COD_FAMILIAParameter = p_COD_FAMILIA.HasValue ?
                new ObjectParameter("P_COD_FAMILIA", p_COD_FAMILIA) :
                new ObjectParameter("P_COD_FAMILIA", typeof(decimal));
    
            var p_ANIO_INSCRIPCIONParameter = p_ANIO_INSCRIPCION.HasValue ?
                new ObjectParameter("P_ANIO_INSCRIPCION", p_ANIO_INSCRIPCION) :
                new ObjectParameter("P_ANIO_INSCRIPCION", typeof(decimal));
    
            var p_NUM_HABITACIONESParameter = p_NUM_HABITACIONES.HasValue ?
                new ObjectParameter("P_NUM_HABITACIONES", p_NUM_HABITACIONES) :
                new ObjectParameter("P_NUM_HABITACIONES", typeof(decimal));
    
            var p_TIPO_VIVIENDAParameter = p_TIPO_VIVIENDA != null ?
                new ObjectParameter("P_TIPO_VIVIENDA", p_TIPO_VIVIENDA) :
                new ObjectParameter("P_TIPO_VIVIENDA", typeof(string));
    
            var p_NUM_INTEGRANTESParameter = p_NUM_INTEGRANTES.HasValue ?
                new ObjectParameter("P_NUM_INTEGRANTES", p_NUM_INTEGRANTES) :
                new ObjectParameter("P_NUM_INTEGRANTES", typeof(decimal));
    
            var p_FK_COD_PERSONAParameter = p_FK_COD_PERSONA.HasValue ?
                new ObjectParameter("P_FK_COD_PERSONA", p_FK_COD_PERSONA) :
                new ObjectParameter("P_FK_COD_PERSONA", typeof(decimal));
    
            var p_ESTACIONAMIENTOParameter = p_ESTACIONAMIENTO != null ?
                new ObjectParameter("P_ESTACIONAMIENTO", p_ESTACIONAMIENTO) :
                new ObjectParameter("P_ESTACIONAMIENTO", typeof(string));
    
            var p_MASCOTA_DESCRIPCIONParameter = p_MASCOTA_DESCRIPCION != null ?
                new ObjectParameter("P_MASCOTA_DESCRIPCION", p_MASCOTA_DESCRIPCION) :
                new ObjectParameter("P_MASCOTA_DESCRIPCION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ActualizarFamilia", p_NUM_BANOSParameter, p_FK_COD_ANTECEDENTESParameter, p_COD_FAMILIAParameter, p_ANIO_INSCRIPCIONParameter, p_NUM_HABITACIONESParameter, p_TIPO_VIVIENDAParameter, p_NUM_INTEGRANTESParameter, p_FK_COD_PERSONAParameter, p_ESTACIONAMIENTOParameter, p_MASCOTA_DESCRIPCIONParameter);
        }
    
        public virtual int EliminarFamilia(Nullable<decimal> p_COD_FAMILIA)
        {
            var p_COD_FAMILIAParameter = p_COD_FAMILIA.HasValue ?
                new ObjectParameter("P_COD_FAMILIA", p_COD_FAMILIA) :
                new ObjectParameter("P_COD_FAMILIA", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EliminarFamilia", p_COD_FAMILIAParameter);
        }
    
        public virtual int CrearAntecedentes(string p_FOTO3, string p_FOTO2, string p_FOTO1, string p_CERT_LABORAL, Nullable<decimal> p_COD_ANTECEDENTES, string p_CERT_RESIDENCIA, string p_CERT_ANTECEDENTES)
        {
            var p_FOTO3Parameter = p_FOTO3 != null ?
                new ObjectParameter("P_FOTO3", p_FOTO3) :
                new ObjectParameter("P_FOTO3", typeof(string));
    
            var p_FOTO2Parameter = p_FOTO2 != null ?
                new ObjectParameter("P_FOTO2", p_FOTO2) :
                new ObjectParameter("P_FOTO2", typeof(string));
    
            var p_FOTO1Parameter = p_FOTO1 != null ?
                new ObjectParameter("P_FOTO1", p_FOTO1) :
                new ObjectParameter("P_FOTO1", typeof(string));
    
            var p_CERT_LABORALParameter = p_CERT_LABORAL != null ?
                new ObjectParameter("P_CERT_LABORAL", p_CERT_LABORAL) :
                new ObjectParameter("P_CERT_LABORAL", typeof(string));
    
            var p_COD_ANTECEDENTESParameter = p_COD_ANTECEDENTES.HasValue ?
                new ObjectParameter("P_COD_ANTECEDENTES", p_COD_ANTECEDENTES) :
                new ObjectParameter("P_COD_ANTECEDENTES", typeof(decimal));
    
            var p_CERT_RESIDENCIAParameter = p_CERT_RESIDENCIA != null ?
                new ObjectParameter("P_CERT_RESIDENCIA", p_CERT_RESIDENCIA) :
                new ObjectParameter("P_CERT_RESIDENCIA", typeof(string));
    
            var p_CERT_ANTECEDENTESParameter = p_CERT_ANTECEDENTES != null ?
                new ObjectParameter("P_CERT_ANTECEDENTES", p_CERT_ANTECEDENTES) :
                new ObjectParameter("P_CERT_ANTECEDENTES", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CrearAntecedentes", p_FOTO3Parameter, p_FOTO2Parameter, p_FOTO1Parameter, p_CERT_LABORALParameter, p_COD_ANTECEDENTESParameter, p_CERT_RESIDENCIAParameter, p_CERT_ANTECEDENTESParameter);
        }
    
        public virtual int ActualizarAntecedentes(string p_FOTO3, string p_FOTO2, string p_FOTO1, string p_CERT_LABORAL, Nullable<decimal> p_COD_ANTECEDENTES, string p_CERT_RESIDENCIA, string p_CERT_ANTECEDENTES)
        {
            var p_FOTO3Parameter = p_FOTO3 != null ?
                new ObjectParameter("P_FOTO3", p_FOTO3) :
                new ObjectParameter("P_FOTO3", typeof(string));
    
            var p_FOTO2Parameter = p_FOTO2 != null ?
                new ObjectParameter("P_FOTO2", p_FOTO2) :
                new ObjectParameter("P_FOTO2", typeof(string));
    
            var p_FOTO1Parameter = p_FOTO1 != null ?
                new ObjectParameter("P_FOTO1", p_FOTO1) :
                new ObjectParameter("P_FOTO1", typeof(string));
    
            var p_CERT_LABORALParameter = p_CERT_LABORAL != null ?
                new ObjectParameter("P_CERT_LABORAL", p_CERT_LABORAL) :
                new ObjectParameter("P_CERT_LABORAL", typeof(string));
    
            var p_COD_ANTECEDENTESParameter = p_COD_ANTECEDENTES.HasValue ?
                new ObjectParameter("P_COD_ANTECEDENTES", p_COD_ANTECEDENTES) :
                new ObjectParameter("P_COD_ANTECEDENTES", typeof(decimal));
    
            var p_CERT_RESIDENCIAParameter = p_CERT_RESIDENCIA != null ?
                new ObjectParameter("P_CERT_RESIDENCIA", p_CERT_RESIDENCIA) :
                new ObjectParameter("P_CERT_RESIDENCIA", typeof(string));
    
            var p_CERT_ANTECEDENTESParameter = p_CERT_ANTECEDENTES != null ?
                new ObjectParameter("P_CERT_ANTECEDENTES", p_CERT_ANTECEDENTES) :
                new ObjectParameter("P_CERT_ANTECEDENTES", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ActualizarAntecedentes", p_FOTO3Parameter, p_FOTO2Parameter, p_FOTO1Parameter, p_CERT_LABORALParameter, p_COD_ANTECEDENTESParameter, p_CERT_RESIDENCIAParameter, p_CERT_ANTECEDENTESParameter);
        }
    
        public virtual int EliminarAntecedentes(Nullable<decimal> p_COD_ALUMNO)
        {
            var p_COD_ALUMNOParameter = p_COD_ALUMNO.HasValue ?
                new ObjectParameter("P_COD_ALUMNO", p_COD_ALUMNO) :
                new ObjectParameter("P_COD_ALUMNO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EliminarAntecedentes", p_COD_ALUMNOParameter);
        }
    
        public virtual int CrearEncargadoCEL(Nullable<decimal> p_FK_COD_CEL, Nullable<decimal> p_FK_COD_PERSONA, Nullable<decimal> p_COD_ENCARGADOCEL)
        {
            var p_FK_COD_CELParameter = p_FK_COD_CEL.HasValue ?
                new ObjectParameter("P_FK_COD_CEL", p_FK_COD_CEL) :
                new ObjectParameter("P_FK_COD_CEL", typeof(decimal));
    
            var p_FK_COD_PERSONAParameter = p_FK_COD_PERSONA.HasValue ?
                new ObjectParameter("P_FK_COD_PERSONA", p_FK_COD_PERSONA) :
                new ObjectParameter("P_FK_COD_PERSONA", typeof(decimal));
    
            var p_COD_ENCARGADOCELParameter = p_COD_ENCARGADOCEL.HasValue ?
                new ObjectParameter("P_COD_ENCARGADOCEL", p_COD_ENCARGADOCEL) :
                new ObjectParameter("P_COD_ENCARGADOCEL", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CrearEncargadoCEL", p_FK_COD_CELParameter, p_FK_COD_PERSONAParameter, p_COD_ENCARGADOCELParameter);
        }
    
        public virtual int ActualizarEncargadoCEL(Nullable<decimal> p_FK_COD_CEL, Nullable<decimal> p_FK_COD_PERSONA, Nullable<decimal> p_COD_ENCARGADOCEL)
        {
            var p_FK_COD_CELParameter = p_FK_COD_CEL.HasValue ?
                new ObjectParameter("P_FK_COD_CEL", p_FK_COD_CEL) :
                new ObjectParameter("P_FK_COD_CEL", typeof(decimal));
    
            var p_FK_COD_PERSONAParameter = p_FK_COD_PERSONA.HasValue ?
                new ObjectParameter("P_FK_COD_PERSONA", p_FK_COD_PERSONA) :
                new ObjectParameter("P_FK_COD_PERSONA", typeof(decimal));
    
            var p_COD_ENCARGADOCELParameter = p_COD_ENCARGADOCEL.HasValue ?
                new ObjectParameter("P_COD_ENCARGADOCEL", p_COD_ENCARGADOCEL) :
                new ObjectParameter("P_COD_ENCARGADOCEL", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ActualizarEncargadoCEL", p_FK_COD_CELParameter, p_FK_COD_PERSONAParameter, p_COD_ENCARGADOCELParameter);
        }
    
        public virtual int EliminarEncargadoCEL(Nullable<decimal> p_COD_ENCARGADOCEL)
        {
            var p_COD_ENCARGADOCELParameter = p_COD_ENCARGADOCEL.HasValue ?
                new ObjectParameter("P_COD_ENCARGADOCEL", p_COD_ENCARGADOCEL) :
                new ObjectParameter("P_COD_ENCARGADOCEL", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EliminarEncargadoCEL", p_COD_ENCARGADOCELParameter);
        }
    
        public virtual int CrearEncargadoCEM(Nullable<decimal> p_FK_COD_PERSONA, Nullable<decimal> p_COD_ENCARGADOCEM)
        {
            var p_FK_COD_PERSONAParameter = p_FK_COD_PERSONA.HasValue ?
                new ObjectParameter("P_FK_COD_PERSONA", p_FK_COD_PERSONA) :
                new ObjectParameter("P_FK_COD_PERSONA", typeof(decimal));
    
            var p_COD_ENCARGADOCEMParameter = p_COD_ENCARGADOCEM.HasValue ?
                new ObjectParameter("P_COD_ENCARGADOCEM", p_COD_ENCARGADOCEM) :
                new ObjectParameter("P_COD_ENCARGADOCEM", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CrearEncargadoCEM", p_FK_COD_PERSONAParameter, p_COD_ENCARGADOCEMParameter);
        }
    
        public virtual int ActualizarEncargadoCEM(Nullable<decimal> p_FK_COD_PERSONA, Nullable<decimal> p_COD_ENCARGADOCEM)
        {
            var p_FK_COD_PERSONAParameter = p_FK_COD_PERSONA.HasValue ?
                new ObjectParameter("P_FK_COD_PERSONA", p_FK_COD_PERSONA) :
                new ObjectParameter("P_FK_COD_PERSONA", typeof(decimal));
    
            var p_COD_ENCARGADOCEMParameter = p_COD_ENCARGADOCEM.HasValue ?
                new ObjectParameter("P_COD_ENCARGADOCEM", p_COD_ENCARGADOCEM) :
                new ObjectParameter("P_COD_ENCARGADOCEM", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ActualizarEncargadoCEM", p_FK_COD_PERSONAParameter, p_COD_ENCARGADOCEMParameter);
        }
    
        public virtual int EliminarEncargadoCEM(Nullable<decimal> p_COD_ENCARGADOCEM)
        {
            var p_COD_ENCARGADOCEMParameter = p_COD_ENCARGADOCEM.HasValue ?
                new ObjectParameter("P_COD_ENCARGADOCEM", p_COD_ENCARGADOCEM) :
                new ObjectParameter("P_COD_ENCARGADOCEM", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EliminarEncargadoCEM", p_COD_ENCARGADOCEMParameter);
        }
    
        public virtual int CrearCEL(string p_DIRECCION, string p_NOMBRE_CENTRO, string p_CORREO, Nullable<decimal> p_COD_CEL, Nullable<decimal> p_TELEFONO, string p_AREA_ESPECIALIZACION, string p_DESCRIPCION, Nullable<decimal> p_FK_COD_CIUDAD, string p_NOM_DIRECTOR)
        {
            var p_DIRECCIONParameter = p_DIRECCION != null ?
                new ObjectParameter("P_DIRECCION", p_DIRECCION) :
                new ObjectParameter("P_DIRECCION", typeof(string));
    
            var p_NOMBRE_CENTROParameter = p_NOMBRE_CENTRO != null ?
                new ObjectParameter("P_NOMBRE_CENTRO", p_NOMBRE_CENTRO) :
                new ObjectParameter("P_NOMBRE_CENTRO", typeof(string));
    
            var p_CORREOParameter = p_CORREO != null ?
                new ObjectParameter("P_CORREO", p_CORREO) :
                new ObjectParameter("P_CORREO", typeof(string));
    
            var p_COD_CELParameter = p_COD_CEL.HasValue ?
                new ObjectParameter("P_COD_CEL", p_COD_CEL) :
                new ObjectParameter("P_COD_CEL", typeof(decimal));
    
            var p_TELEFONOParameter = p_TELEFONO.HasValue ?
                new ObjectParameter("P_TELEFONO", p_TELEFONO) :
                new ObjectParameter("P_TELEFONO", typeof(decimal));
    
            var p_AREA_ESPECIALIZACIONParameter = p_AREA_ESPECIALIZACION != null ?
                new ObjectParameter("P_AREA_ESPECIALIZACION", p_AREA_ESPECIALIZACION) :
                new ObjectParameter("P_AREA_ESPECIALIZACION", typeof(string));
    
            var p_DESCRIPCIONParameter = p_DESCRIPCION != null ?
                new ObjectParameter("P_DESCRIPCION", p_DESCRIPCION) :
                new ObjectParameter("P_DESCRIPCION", typeof(string));
    
            var p_FK_COD_CIUDADParameter = p_FK_COD_CIUDAD.HasValue ?
                new ObjectParameter("P_FK_COD_CIUDAD", p_FK_COD_CIUDAD) :
                new ObjectParameter("P_FK_COD_CIUDAD", typeof(decimal));
    
            var p_NOM_DIRECTORParameter = p_NOM_DIRECTOR != null ?
                new ObjectParameter("P_NOM_DIRECTOR", p_NOM_DIRECTOR) :
                new ObjectParameter("P_NOM_DIRECTOR", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CrearCEL", p_DIRECCIONParameter, p_NOMBRE_CENTROParameter, p_CORREOParameter, p_COD_CELParameter, p_TELEFONOParameter, p_AREA_ESPECIALIZACIONParameter, p_DESCRIPCIONParameter, p_FK_COD_CIUDADParameter, p_NOM_DIRECTORParameter);
        }
    
        public virtual int ActualizarCEL(string p_DIRECCION, string p_NOMBRE_CENTRO, string p_CORREO, Nullable<decimal> p_COD_CEL, Nullable<decimal> p_TELEFONO, string p_AREA_ESPECIALIZACION, string p_DESCRIPCION, Nullable<decimal> p_FK_COD_CIUDAD, string p_NOM_DIRECTOR)
        {
            var p_DIRECCIONParameter = p_DIRECCION != null ?
                new ObjectParameter("P_DIRECCION", p_DIRECCION) :
                new ObjectParameter("P_DIRECCION", typeof(string));
    
            var p_NOMBRE_CENTROParameter = p_NOMBRE_CENTRO != null ?
                new ObjectParameter("P_NOMBRE_CENTRO", p_NOMBRE_CENTRO) :
                new ObjectParameter("P_NOMBRE_CENTRO", typeof(string));
    
            var p_CORREOParameter = p_CORREO != null ?
                new ObjectParameter("P_CORREO", p_CORREO) :
                new ObjectParameter("P_CORREO", typeof(string));
    
            var p_COD_CELParameter = p_COD_CEL.HasValue ?
                new ObjectParameter("P_COD_CEL", p_COD_CEL) :
                new ObjectParameter("P_COD_CEL", typeof(decimal));
    
            var p_TELEFONOParameter = p_TELEFONO.HasValue ?
                new ObjectParameter("P_TELEFONO", p_TELEFONO) :
                new ObjectParameter("P_TELEFONO", typeof(decimal));
    
            var p_AREA_ESPECIALIZACIONParameter = p_AREA_ESPECIALIZACION != null ?
                new ObjectParameter("P_AREA_ESPECIALIZACION", p_AREA_ESPECIALIZACION) :
                new ObjectParameter("P_AREA_ESPECIALIZACION", typeof(string));
    
            var p_DESCRIPCIONParameter = p_DESCRIPCION != null ?
                new ObjectParameter("P_DESCRIPCION", p_DESCRIPCION) :
                new ObjectParameter("P_DESCRIPCION", typeof(string));
    
            var p_FK_COD_CIUDADParameter = p_FK_COD_CIUDAD.HasValue ?
                new ObjectParameter("P_FK_COD_CIUDAD", p_FK_COD_CIUDAD) :
                new ObjectParameter("P_FK_COD_CIUDAD", typeof(decimal));
    
            var p_NOM_DIRECTORParameter = p_NOM_DIRECTOR != null ?
                new ObjectParameter("P_NOM_DIRECTOR", p_NOM_DIRECTOR) :
                new ObjectParameter("P_NOM_DIRECTOR", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ActualizarCEL", p_DIRECCIONParameter, p_NOMBRE_CENTROParameter, p_CORREOParameter, p_COD_CELParameter, p_TELEFONOParameter, p_AREA_ESPECIALIZACIONParameter, p_DESCRIPCIONParameter, p_FK_COD_CIUDADParameter, p_NOM_DIRECTORParameter);
        }
    
        public virtual int EliminarCEL(Nullable<decimal> p_COD_CEL)
        {
            var p_COD_CELParameter = p_COD_CEL.HasValue ?
                new ObjectParameter("P_COD_CEL", p_COD_CEL) :
                new ObjectParameter("P_COD_CEL", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EliminarCEL", p_COD_CELParameter);
        }
    
        public virtual int CrearProgramaEstudio(Nullable<System.DateTime> p_FECHA_LIMITE_POSTULACION, Nullable<decimal> p_NUM_MIN_ALUMNO, Nullable<decimal> p_FK_COD_TIPOPROGRAMA, Nullable<decimal> p_FK_COD_ENCARGADOCEM, Nullable<decimal> p_COD_PROGRAMA, string p_DURACION, string p_AREA_CONOCIMIENTO, Nullable<decimal> p_NUM_MAX_ALUMNO, Nullable<decimal> p_FK_COD_PAIS, string p_DESCRIPCION, string p_NOMBRE_PROGRAMA)
        {
            var p_FECHA_LIMITE_POSTULACIONParameter = p_FECHA_LIMITE_POSTULACION.HasValue ?
                new ObjectParameter("P_FECHA_LIMITE_POSTULACION", p_FECHA_LIMITE_POSTULACION) :
                new ObjectParameter("P_FECHA_LIMITE_POSTULACION", typeof(System.DateTime));
    
            var p_NUM_MIN_ALUMNOParameter = p_NUM_MIN_ALUMNO.HasValue ?
                new ObjectParameter("P_NUM_MIN_ALUMNO", p_NUM_MIN_ALUMNO) :
                new ObjectParameter("P_NUM_MIN_ALUMNO", typeof(decimal));
    
            var p_FK_COD_TIPOPROGRAMAParameter = p_FK_COD_TIPOPROGRAMA.HasValue ?
                new ObjectParameter("P_FK_COD_TIPOPROGRAMA", p_FK_COD_TIPOPROGRAMA) :
                new ObjectParameter("P_FK_COD_TIPOPROGRAMA", typeof(decimal));
    
            var p_FK_COD_ENCARGADOCEMParameter = p_FK_COD_ENCARGADOCEM.HasValue ?
                new ObjectParameter("P_FK_COD_ENCARGADOCEM", p_FK_COD_ENCARGADOCEM) :
                new ObjectParameter("P_FK_COD_ENCARGADOCEM", typeof(decimal));
    
            var p_COD_PROGRAMAParameter = p_COD_PROGRAMA.HasValue ?
                new ObjectParameter("P_COD_PROGRAMA", p_COD_PROGRAMA) :
                new ObjectParameter("P_COD_PROGRAMA", typeof(decimal));
    
            var p_DURACIONParameter = p_DURACION != null ?
                new ObjectParameter("P_DURACION", p_DURACION) :
                new ObjectParameter("P_DURACION", typeof(string));
    
            var p_AREA_CONOCIMIENTOParameter = p_AREA_CONOCIMIENTO != null ?
                new ObjectParameter("P_AREA_CONOCIMIENTO", p_AREA_CONOCIMIENTO) :
                new ObjectParameter("P_AREA_CONOCIMIENTO", typeof(string));
    
            var p_NUM_MAX_ALUMNOParameter = p_NUM_MAX_ALUMNO.HasValue ?
                new ObjectParameter("P_NUM_MAX_ALUMNO", p_NUM_MAX_ALUMNO) :
                new ObjectParameter("P_NUM_MAX_ALUMNO", typeof(decimal));
    
            var p_FK_COD_PAISParameter = p_FK_COD_PAIS.HasValue ?
                new ObjectParameter("P_FK_COD_PAIS", p_FK_COD_PAIS) :
                new ObjectParameter("P_FK_COD_PAIS", typeof(decimal));
    
            var p_DESCRIPCIONParameter = p_DESCRIPCION != null ?
                new ObjectParameter("P_DESCRIPCION", p_DESCRIPCION) :
                new ObjectParameter("P_DESCRIPCION", typeof(string));
    
            var p_NOMBRE_PROGRAMAParameter = p_NOMBRE_PROGRAMA != null ?
                new ObjectParameter("P_NOMBRE_PROGRAMA", p_NOMBRE_PROGRAMA) :
                new ObjectParameter("P_NOMBRE_PROGRAMA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CrearProgramaEstudio", p_FECHA_LIMITE_POSTULACIONParameter, p_NUM_MIN_ALUMNOParameter, p_FK_COD_TIPOPROGRAMAParameter, p_FK_COD_ENCARGADOCEMParameter, p_COD_PROGRAMAParameter, p_DURACIONParameter, p_AREA_CONOCIMIENTOParameter, p_NUM_MAX_ALUMNOParameter, p_FK_COD_PAISParameter, p_DESCRIPCIONParameter, p_NOMBRE_PROGRAMAParameter);
        }
    
        public virtual int ActualizarProgramaEstudio(Nullable<System.DateTime> p_FECHA_LIMITE_POSTULACION, Nullable<decimal> p_NUM_MIN_ALUMNO, Nullable<decimal> p_FK_COD_TIPOPROGRAMA, Nullable<decimal> p_FK_COD_ENCARGADOCEM, Nullable<decimal> p_COD_PROGRAMA, string p_DURACION, string p_AREA_CONOCIMIENTO, Nullable<decimal> p_NUM_MAX_ALUMNO, Nullable<decimal> p_FK_COD_PAIS, string p_DESCRIPCION, string p_NOMBRE_PROGRAMA)
        {
            var p_FECHA_LIMITE_POSTULACIONParameter = p_FECHA_LIMITE_POSTULACION.HasValue ?
                new ObjectParameter("P_FECHA_LIMITE_POSTULACION", p_FECHA_LIMITE_POSTULACION) :
                new ObjectParameter("P_FECHA_LIMITE_POSTULACION", typeof(System.DateTime));
    
            var p_NUM_MIN_ALUMNOParameter = p_NUM_MIN_ALUMNO.HasValue ?
                new ObjectParameter("P_NUM_MIN_ALUMNO", p_NUM_MIN_ALUMNO) :
                new ObjectParameter("P_NUM_MIN_ALUMNO", typeof(decimal));
    
            var p_FK_COD_TIPOPROGRAMAParameter = p_FK_COD_TIPOPROGRAMA.HasValue ?
                new ObjectParameter("P_FK_COD_TIPOPROGRAMA", p_FK_COD_TIPOPROGRAMA) :
                new ObjectParameter("P_FK_COD_TIPOPROGRAMA", typeof(decimal));
    
            var p_FK_COD_ENCARGADOCEMParameter = p_FK_COD_ENCARGADOCEM.HasValue ?
                new ObjectParameter("P_FK_COD_ENCARGADOCEM", p_FK_COD_ENCARGADOCEM) :
                new ObjectParameter("P_FK_COD_ENCARGADOCEM", typeof(decimal));
    
            var p_COD_PROGRAMAParameter = p_COD_PROGRAMA.HasValue ?
                new ObjectParameter("P_COD_PROGRAMA", p_COD_PROGRAMA) :
                new ObjectParameter("P_COD_PROGRAMA", typeof(decimal));
    
            var p_DURACIONParameter = p_DURACION != null ?
                new ObjectParameter("P_DURACION", p_DURACION) :
                new ObjectParameter("P_DURACION", typeof(string));
    
            var p_AREA_CONOCIMIENTOParameter = p_AREA_CONOCIMIENTO != null ?
                new ObjectParameter("P_AREA_CONOCIMIENTO", p_AREA_CONOCIMIENTO) :
                new ObjectParameter("P_AREA_CONOCIMIENTO", typeof(string));
    
            var p_NUM_MAX_ALUMNOParameter = p_NUM_MAX_ALUMNO.HasValue ?
                new ObjectParameter("P_NUM_MAX_ALUMNO", p_NUM_MAX_ALUMNO) :
                new ObjectParameter("P_NUM_MAX_ALUMNO", typeof(decimal));
    
            var p_FK_COD_PAISParameter = p_FK_COD_PAIS.HasValue ?
                new ObjectParameter("P_FK_COD_PAIS", p_FK_COD_PAIS) :
                new ObjectParameter("P_FK_COD_PAIS", typeof(decimal));
    
            var p_DESCRIPCIONParameter = p_DESCRIPCION != null ?
                new ObjectParameter("P_DESCRIPCION", p_DESCRIPCION) :
                new ObjectParameter("P_DESCRIPCION", typeof(string));
    
            var p_NOMBRE_PROGRAMAParameter = p_NOMBRE_PROGRAMA != null ?
                new ObjectParameter("P_NOMBRE_PROGRAMA", p_NOMBRE_PROGRAMA) :
                new ObjectParameter("P_NOMBRE_PROGRAMA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ActualizarProgramaEstudio", p_FECHA_LIMITE_POSTULACIONParameter, p_NUM_MIN_ALUMNOParameter, p_FK_COD_TIPOPROGRAMAParameter, p_FK_COD_ENCARGADOCEMParameter, p_COD_PROGRAMAParameter, p_DURACIONParameter, p_AREA_CONOCIMIENTOParameter, p_NUM_MAX_ALUMNOParameter, p_FK_COD_PAISParameter, p_DESCRIPCIONParameter, p_NOMBRE_PROGRAMAParameter);
        }
    
        public virtual int EliminarProgramaEstudio(Nullable<decimal> p_COD_PROGRAMA)
        {
            var p_COD_PROGRAMAParameter = p_COD_PROGRAMA.HasValue ?
                new ObjectParameter("P_COD_PROGRAMA", p_COD_PROGRAMA) :
                new ObjectParameter("P_COD_PROGRAMA", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EliminarProgramaEstudio", p_COD_PROGRAMAParameter);
        }
    
        public virtual int CrearPostulacionPrograma(Nullable<decimal> p_FK_COD_CEL, Nullable<decimal> p_FK_COD_PROGRAMA, Nullable<decimal> p_FK_COD_ENCARGADOCEM, Nullable<System.DateTime> p_FECHA, Nullable<decimal> p_COD_POSTULACIONPROGRAMA, Nullable<decimal> p_FK_COD_ESTADO)
        {
            var p_FK_COD_CELParameter = p_FK_COD_CEL.HasValue ?
                new ObjectParameter("P_FK_COD_CEL", p_FK_COD_CEL) :
                new ObjectParameter("P_FK_COD_CEL", typeof(decimal));
    
            var p_FK_COD_PROGRAMAParameter = p_FK_COD_PROGRAMA.HasValue ?
                new ObjectParameter("P_FK_COD_PROGRAMA", p_FK_COD_PROGRAMA) :
                new ObjectParameter("P_FK_COD_PROGRAMA", typeof(decimal));
    
            var p_FK_COD_ENCARGADOCEMParameter = p_FK_COD_ENCARGADOCEM.HasValue ?
                new ObjectParameter("P_FK_COD_ENCARGADOCEM", p_FK_COD_ENCARGADOCEM) :
                new ObjectParameter("P_FK_COD_ENCARGADOCEM", typeof(decimal));
    
            var p_FECHAParameter = p_FECHA.HasValue ?
                new ObjectParameter("P_FECHA", p_FECHA) :
                new ObjectParameter("P_FECHA", typeof(System.DateTime));
    
            var p_COD_POSTULACIONPROGRAMAParameter = p_COD_POSTULACIONPROGRAMA.HasValue ?
                new ObjectParameter("P_COD_POSTULACIONPROGRAMA", p_COD_POSTULACIONPROGRAMA) :
                new ObjectParameter("P_COD_POSTULACIONPROGRAMA", typeof(decimal));
    
            var p_FK_COD_ESTADOParameter = p_FK_COD_ESTADO.HasValue ?
                new ObjectParameter("P_FK_COD_ESTADO", p_FK_COD_ESTADO) :
                new ObjectParameter("P_FK_COD_ESTADO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CrearPostulacionPrograma", p_FK_COD_CELParameter, p_FK_COD_PROGRAMAParameter, p_FK_COD_ENCARGADOCEMParameter, p_FECHAParameter, p_COD_POSTULACIONPROGRAMAParameter, p_FK_COD_ESTADOParameter);
        }
    
        public virtual int ActualizarPostulacionPrograma(Nullable<decimal> p_FK_COD_CEL, Nullable<decimal> p_FK_COD_PROGRAMA, Nullable<decimal> p_FK_COD_ENCARGADOCEM, Nullable<System.DateTime> p_FECHA, Nullable<decimal> p_COD_POSTULACIONPROGRAMA, Nullable<decimal> p_FK_COD_ESTADO)
        {
            var p_FK_COD_CELParameter = p_FK_COD_CEL.HasValue ?
                new ObjectParameter("P_FK_COD_CEL", p_FK_COD_CEL) :
                new ObjectParameter("P_FK_COD_CEL", typeof(decimal));
    
            var p_FK_COD_PROGRAMAParameter = p_FK_COD_PROGRAMA.HasValue ?
                new ObjectParameter("P_FK_COD_PROGRAMA", p_FK_COD_PROGRAMA) :
                new ObjectParameter("P_FK_COD_PROGRAMA", typeof(decimal));
    
            var p_FK_COD_ENCARGADOCEMParameter = p_FK_COD_ENCARGADOCEM.HasValue ?
                new ObjectParameter("P_FK_COD_ENCARGADOCEM", p_FK_COD_ENCARGADOCEM) :
                new ObjectParameter("P_FK_COD_ENCARGADOCEM", typeof(decimal));
    
            var p_FECHAParameter = p_FECHA.HasValue ?
                new ObjectParameter("P_FECHA", p_FECHA) :
                new ObjectParameter("P_FECHA", typeof(System.DateTime));
    
            var p_COD_POSTULACIONPROGRAMAParameter = p_COD_POSTULACIONPROGRAMA.HasValue ?
                new ObjectParameter("P_COD_POSTULACIONPROGRAMA", p_COD_POSTULACIONPROGRAMA) :
                new ObjectParameter("P_COD_POSTULACIONPROGRAMA", typeof(decimal));
    
            var p_FK_COD_ESTADOParameter = p_FK_COD_ESTADO.HasValue ?
                new ObjectParameter("P_FK_COD_ESTADO", p_FK_COD_ESTADO) :
                new ObjectParameter("P_FK_COD_ESTADO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ActualizarPostulacionPrograma", p_FK_COD_CELParameter, p_FK_COD_PROGRAMAParameter, p_FK_COD_ENCARGADOCEMParameter, p_FECHAParameter, p_COD_POSTULACIONPROGRAMAParameter, p_FK_COD_ESTADOParameter);
        }
    
        public virtual int EliminarPostulacionPrograma(Nullable<decimal> p_COD_POSTULACIONPROGRAMA)
        {
            var p_COD_POSTULACIONPROGRAMAParameter = p_COD_POSTULACIONPROGRAMA.HasValue ?
                new ObjectParameter("P_COD_POSTULACIONPROGRAMA", p_COD_POSTULACIONPROGRAMA) :
                new ObjectParameter("P_COD_POSTULACIONPROGRAMA", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EliminarPostulacionPrograma", p_COD_POSTULACIONPROGRAMAParameter);
        }
    }
}
